name: run main.py

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # install the packages needed
          
      - name: execute py script # run main.py
        env:
            KASSAL_BEARER_TOKEN: ${{ secrets.KASSAL_BEARER_TOKEN }} # Set your secret in GitHub
            MONGO_URL: ${{ secrets.MONGO_URL }} # Set your secret in GitHub
        run: python main.py